# Generated by Django 6.0.3 on 2026-03-31 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_riderprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderprofile',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='traderprofile',
            old_name='user',
            new_name='username',
        ),
    ]
