# Generated by Django 6.0.3 on 2026-04-01 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_user_riderprofile_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderprofile',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='traderprofile',
            old_name='username',
            new_name='user',
        ),
    ]
