# Generated by Django 6.0.3 on 2026-04-04 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_username_riderprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField()),
                ('delivery_time', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('packageDesc', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.riderprofile')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.traderprofile')),
            ],
        ),
    ]
