# Generated by Django 6.0.3 on 2026-04-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderprofile',
            old_name='license_number',
            new_name='licenseplate_number',
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='traderprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
