# Generated by Django 6.0.3 on 2026-04-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_license_number_riderprofile_licenseplate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderprofile',
            name='floor',
            field=models.IntegerField(blank=True, default=1, max_length=2),
            preserve_default=False,
        ),
    ]
