# Generated by Django 6.0.3 on 2026-04-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_traderprofile_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=255)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='lsp_logos/')),
            ],
        ),
        migrations.AlterField(
            model_name='traderprofile',
            name='floor',
            field=models.IntegerField(blank=True),
        ),
    ]
