# Generated by Django 6.0.3 on 2026-04-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_lsp_alter_traderprofile_floor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LSP',
            new_name='LSPs',
        ),
    ]
