# Generated by Django 6.0.3 on 2026-04-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
