# Generated by Django 6.0.3 on 2026-04-11 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_request_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.riderprofile'),
        ),
    ]
