# Generated by Django 6.0.3 on 2026-04-11 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_request_rider'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.request')),
            ],
        ),
    ]
