# Generated by Django 6.0.3 on 2026-04-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_deliveryevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryevents',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
