# Generated by Django 6.0.3 on 2026-04-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_deliveryevents_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='vehicletype',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
