# Generated by Django 6.0.3 on 2026-04-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_riderprofile_vehicletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
