# Generated by Django 6.0.3 on 2026-04-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_riderprofile_is_busy_riderprofile_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispatching', 'Dispatching'), ('assigned', 'Assigned'), ('manual', 'Manual Assignment'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
