# Generated by Django 6.0.3 on 2026-04-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderprofile',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
