# Generated by Django 6.0.3 on 2026-05-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_traderprofile_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('Single order', 'Batch order')], default='Single order', max_length=50),
        ),
        migrations.AlterField(
            model_name='traderprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='traderprofile',
            name='stall_number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
