# Generated by Django 6.0.3 on 2026-05-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_request_type_alter_traderprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
