# Generated by Django 6.0.3 on 2026-05-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_traderprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderprofile',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
