"""
Django settings for letsapp project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, seedefault_headers
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+!2&vpt8!zmog2q6f8b6jg3s$p!6c@o$ixh7uj_of_goeq(fqq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = [
    "b9cf-102-209-18-110.ngrok-free.app",
    "localhost",
    "127.0.0.1",
    ]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8080",
    "http://localhost:8080",
    "http://localhost:8000",   
    "http://127.0.0.1:8000",
    "https://b9cf-102-209-18-110.ngrok-free.app",
]


CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8080",
    "http://localhost:8080",
    "http://localhost:8000",   
    "http://127.0.0.1:8000",
    "https://b9cf-102-209-18-110.ngrok-free.app",
]




# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'backend',
    'letsapp',
    'rest_framework',
    'rest_framework.authtoken',
    'channels',
    'django_celery_results',
  

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}


ROOT_URLCONF = 'letsapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "dist" ],  # global templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
ASGI_APPLICATION = 'letsapp.asgi.application'

#WSGI_APPLICATION = 'letsapp.wsgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [{
                'address': 'rediss://default:gQAAAAAAATeEAAIncDI0MmVkZjcyYTc0ZmQ0ZjI2YTJmNDcxNjg0N2YzODkwNXAyNzk3NDg@wanted-fowl-79748.upstash.io:6379',
                'ssl_cert_reqs': None,
            }],
        },
    }
}


CELERY_BROKER_URL = 'rediss://default:gQAAAAAAATeEAAIncDI0MmVkZjcyYTc0ZmQ0ZjI2YTJmNDcxNjg0N2YzODkwNXAyNzk3NDg@wanted-fowl-79748.upstash.io:6379'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "localhost"
EMAIL_PORT = 25

# MPESA Configuration 
MPESA_CONFIG = {
    'BASE_URL': 'https://sandbox.safaricom.co.ke',
    'CONSUMER_KEY': 'z6cSKnVVCiZZDTJsGZz4ZETlaMdva0gmERSmsSWqdqTX6XgD',
    'CONSUMER_SECRET': 'KFmC9Dkv7oVdgXa3gHM1iaNLhlTItKozC3AG6Obxp0AJgRnCKBSag94GYiKOVBP3',
    'BUSINESS_SHORT_CODE': '174379',
    'PASSKEY': 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919',
    'CALLBACK_URL': 'https://b9cf-102-209-18-110.ngrok-free.app/mpesa/callback/', 
    
    'INITIATOR_NAME': 'testapi',

}
# static files configuration

# Where collectstatic will put all static files for production
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "dist",
]
